/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfTestExcelTableModel.java
 *
 * Created on Oct 28, 2010, 3:31:48 PM
 */

package dailyfinancemanager;

import DAO.BasicFunction;
import DAO.CopyAllFileFunction;
import DAO.DailyFinanceFunction;
import DAO.DataCustomerMobivi;
import DAO.ExcelFileHelper;
import DAO.ExcelTableModel;
import DAO.HHCTHourFunction;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Administrator
 */
public class jfTestExcelTableModel extends javax.swing.JFrame {

    /** Creates new form jfTestExcelTableModel */
    public jfTestExcelTableModel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButton1.setText("bcdt hang tuan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("tong hop nhieu file excel lam 1 file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //jfOnprocess jf = new jfOnprocess();

        //jf.pack();
        //jf.setVisible(true);
        //jf.DoFunction();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //---------------------------------------------------------
        //tao 1 thread

        //---------------------------------------------------------
        //lay danh sach file torng thu muc
        String[] strListFiles;
        //http://www.rgagnon.com/javadetails/java-0370.html
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showDialog(null, null) == JFileChooser.CANCEL_OPTION)
        {
            //chooser.getCurrentDirectory();
            //this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            return;
        }

        strListFiles = chooser.getSelectedFile().list(new FilenameFilter() {

            public boolean accept(File file, String string) {
                //throw new UnsupportedOperationException("Not supported yet.");

                if((new File(file, string)).isDirectory()) return false;

                if(!string.endsWith("xls")) return false;

                return true;
            }
        });
        DailyFinanceFunction bf = new DailyFinanceFunction();

        for (int i = 0; i < strListFiles.length; i++) {
            ExcelTableModel tb = null;
            try {
                // TODO add your handling code here:
                tb = ExcelFileHelper.GetDataFromFile(chooser.getSelectedFile() + "\\" + strListFiles[i]);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }

            //File f = new File(strListFiles[i]);
            //String[] strSplitName = strListFiles[i].split(" ");
            bf.SetFileName(strListFiles[i].replaceAll(".xls", ""));
            bf.DoFunction(tb);

            try {
                ExcelFileHelper.SaveDataToFile(chooser.getSelectedFile() +  "\\kq" + String.valueOf(i) + ".xls", "Sheet1", bf.GetResult());
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //---------------------------------------------------------
        //lay danh sach file torng thu muc
        String[] strListFiles;
        //http://www.rgagnon.com/javadetails/java-0370.html
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showDialog(null, null) == JFileChooser.CANCEL_OPTION)
        {
            //chooser.getCurrentDirectory();
            //this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            return;
        }

        strListFiles = chooser.getSelectedFile().list(new FilenameFilter() {

            public boolean accept(File file, String string) {
                //throw new UnsupportedOperationException("Not supported yet.");

                if((new File(file, string)).isDirectory()) return false;

                if(!string.endsWith("xls")) return false;

                return true;
            }
        });

        //DailyFinanceFunction bf = new DailyFinanceFunction();
        CopyAllFileFunction bf = new CopyAllFileFunction();
        String[] arrHeaderName = {"Mã hàng",
            "Tên hàng",
            "Số lượng",
            "Thành tiền"};

        int[] arrHeadderNeeded = {1, 2, 5, 11};

        bf.SetAttribute(CopyAllFileFunction.Attribute.HEADER_COLUMNS, arrHeaderName);
        bf.SetAttribute(CopyAllFileFunction.Attribute.COLUMNS_NEEDED_COPY, arrHeadderNeeded);

        bf.PreDoFunctionOneTime(null);

        for (int i = 0; i < strListFiles.length; i++) {
            ExcelTableModel tb = null;
            try {
                // TODO add your handling code here:
                tb = ExcelFileHelper.GetDataFromFile(chooser.getSelectedFile() + "\\" + strListFiles[i]);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }

            bf.SetFileName(strListFiles[i].replaceAll(".xls", ""));
            bf.DoFunction(tb);

            try {
                ExcelFileHelper.SaveDataToFile(chooser.getSelectedFile() +  "\\kq" + String.valueOf(i) + ".xls", "Sheet1", bf.GetResult());
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //DailyFinanceFunction bf = new DailyFinanceFunction();
        DataCustomerMobivi bf = new DataCustomerMobivi();

        ExcelTableModel tbData = null;
        ExcelTableModel tbCity = null;
            try {
                // TODO add your handling code here:
                tbData = ExcelFileHelper.GetDataFromFile("C:\\data.xls");
                tbCity = ExcelFileHelper.GetDataFromFile("C:\\city.xls");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }
        //tao data cho city va state
        String[] arrState = new String[tbCity.getRowCount()];
        for (int i = 0; i < tbCity.getRowCount(); i++) {
            arrState[i] = new String();
            arrState[i] = tbCity.getValueAtString(i, 0);

        }
        bf.SetAttribute(DataCustomerMobivi.Attribute.STATE, arrState);
        //----
        String[] arrCity = new String[tbCity.getRowCount()];
        for (int i = 0; i < tbCity.getRowCount(); i++) {
            arrCity[i] = new String();
            arrCity[i] = tbCity.getValueAtString(i, 1);

        }
        bf.SetAttribute(DataCustomerMobivi.Attribute.CITY, arrCity);

        bf.DoFunction(tbData);

        try {
                ExcelFileHelper.SaveDataToFile("C:\\Result.xls", "Sheet1", bf.GetResult());
            } catch (IOException ex) {
                Logger.getLogger(jfTestExcelTableModel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTestExcelTableModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
